### ISSUE TITLE
Training phase runtime

### ISSUE THREAD

**Issue by lisaalaz** [rainavyas/attack-comparative-assessment#2]
Hi, thank you for your interesting paper _Is LLM-as-a-Judge Robust? Investigating Universal Adversarial Attacks on Zero-shot LLM Assessment_.

Do I understand correctly that at training you iterate over the 20,000-word vocabulary and thus, since you select 4 words, you make (20,000 * n_samples * 4) inference calls, or am I missing something?

It would be useful for us to know how long you think it might take to run the training phase, approximately?

Many thanks!

**Comment by rainavyas** [comment]
Hi, thanks for your question!

Yes, the order of magnitude is as you have stated for absolute scoring and twice that for comparative assessment (to handle position bias). See Algorithm 1 in the paper: https://arxiv.org/pdf/[2402.14016](https://arxiv.org/pdf/2402.14016)

The training time depends on the dataset and the form of assessment. The training time for the attack will also depend on the size of the model used. Points to note:

- Comparative assessment has twice as many inference calls as Absolute Scoring
- Comparative assessment has a much larger input prompt (as it includes two candidates summaries/conversations to evaluate) so inference is more than twice as slow for comparative assessment than absolute scoring
- SummEval has longer candidate responses in general than TopicalChat so each inference is slower for SummEval on average
- The training of the attacks in all of our experiments were done for FlanT5-xl

Estimated training times depend very much on the available computational resources. **Note that all of these experiments can be parallised over the vocabulary being searched** In https://github.com/rainavyas/attack-comparative-assessment/blob/main/src/tools/args.py you will find that `array_job_id` and `array_job_size` parameters will permit you to send the training jobs over specified chunks of the search vocabulary.

 It has been a while since these experiments were run, but here are some ballpark numbers if you do not parallelise to run `train_attack.py` (i.e. to find the next attack word):

Using a 40GB A100 GPU machine:
 - SummEval comparative assessment: 48 hours
 - SummEval absolute scoring: 18 hours
 - TopicalChat comparative assessment: 20 hours
 - TopicalChat absolute scoring: 4-5 hours
